[build]
  functions = "netlify/functions"
[build.environment]
  NETLIFY = "true"
  GO_IMPORT_PATH = "github.com/Sociosarbis/video-entertainment"
  GO111MODULE = "on"
[dev]
  functions = "netlify/functions"
[[redirects]]
  from = "/book.BookService/*"
  to = "https://sociosarbis-media-player.netlify.app/.netlify/functions/grpc"
  status = 200